[package]
name = "Voxi"
version = "1.16.0"
edition = "2021"
rust-version = "1.80"

[[bin]]
name = "Voxi"
path = "src/main.rs"

[dependencies]
windows = { version = "0.52.0", features = [
    "Win32_Media_Speech",
    "Win32_System_ApplicationInstallationAndServicing",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_Security",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
] }
arboard = { version = "3.6", default-features = false }
regex = "1.12"

[build-dependencies]
winresource = { version = "0.1.31", default-features = false }

[profile.release]
lto = true
codegen-units = 1
strip = true
